### ISSUE TITLE
Inicialização

### ISSUE THREAD

**Issue by beatrizcanhaborges** [Joel-Baptista/PSR_TP2_G3#1]
Olá a todos, 
Estou um bocado confusa com a cena do json confesso :(
Já a criei e já la pus os limites que estão no guião.
Também criei o color_segmenter.py mas nao sei porquê não me está a dar resultado da imagem segmentada.
Vou trabalhar nisto à tarde e ver se consigo avançar mais.
Boa continuação

**Comment by ghdrope** [comment]
Depois de falarmos do código de segmentação com globais e ser aceite, vou colocar comentários e alterar a localização dele para o diretório principal.
