### ISSUE TITLE
Comandos por Teclado

### ISSUE THREAD

**Issue by Joel-Baptista** [Joel-Baptista/PSR_TP2_G3#3]
@tiagomateus25 se conseguires hoje, implementa a categoria "Comandos por Teclado" no programa ar_paint.py. Tenta inicializar o argparse numa função à parte para uma melhor organização

**Comment by tiagomfonte** [comment]
okey dokey

**Comment by tiagomfonte** [comment]
Ja fiz alguns comandos para o ar paint e um argparse com as duas primeiras funcionalidades
Malta, ha aqui cenas que eu nao estou bem a entender, se pudessemos fazer reunião ficaria agradecido, sexta ou assim :))
