### ISSUE TITLE
Siga trabalhar malta

### ISSUE THREAD

**Issue by Joel-Baptista** [Joel-Baptista/PSR_TP2_G3#4]
@tiagomateus25 @ghdrope @beatrizcanhaborges , pessoal, quem quiser trabalhar hoje, sugiro "embelezar" o programa antes de passarmos para os desafios, tanto em questões de output com em estrutura do código.

**Comment by tiagomfonte** [comment]
eu posso fazer isso
outra cena o color segmenter funiona vos? a mim fica completamente a preto, nao sei se é do meu pycharm ou assim, tento mover nas trackbars e nada muda

**Comment by tiagomfonte** [comment]
caguem no que escrevi acima ahah

**Comment by ghdrope** [comment]
Eu neste momento durante a tarde estou a trabalhar no estado de arte da minha tese, mas depois do jantar vou pegar nisto!

**Comment by beatrizcanhaborges** [comment]
vou embelezar o programa agora 
depois acho que tenho uma ideia para a funcionalidade 3 vou testá-la a ver se funciona
