### ISSUE TITLE
Extra

### ISSUE THREAD

**Issue by ghdrope** [Joel-Baptista/PSR_TP2_G3#5]
Boas,
Vi nos parâmetros de avaliação que há pontos para um extra (10% penso).
Basicamente, pensei em implementarmos para além da troca de cores por controlos por teclado, uma troca de cores usando a window onde se está a desenhar.
Colocaríamos três quadrados no topo da window, com cada cor, e ao levar o telemóvel ao quadrado ele muda de cor. (Ver imagem)
![image](https://user-images.githubusercontent.com/92882231/142738460-8c174b13-5e8b-4294-b594-69d5fe90011a.jpeg)

**Comment by ghdrope** [comment]
Todos os inputs mencionados de letras, vou implementar com maiuscúlas também, assim caso alguém esteja distraído com o Caps Lock ligado o programa também lê bem o pedido

**Comment by Joel-Baptista** [comment]
Tenho também uma ideia. Quando clicarmos no "p" usa-se uma cor "personalizada" que é a cor que está no ecran do telemovel
